Feat/fuse verifying singleton paymaster
fuseio/fuse-paymasters pull request #1
Opened 2023-07-18 10:23 UTC by maorstamati

Created Fuse Verifying Singleton Paymaster contract

2023-07-23 10:28 UTC, leonprou requested changes
Looks good!
I've added some comments and remarks. Two general question:
- Is there any tests? Can we adjust the current tests in the biconomy/etherspot repo?
- Can we create a new repo with our own paymaster? Not sure if we need other paymasters and all that clutter

2023-07-23 10:28 UTC, leonprou commented on .deps/npm/@account-abstraction/contracts@0.5.0/interfaces/UserOperation.sol
> +pragma solidity ^0.8.12;
You can use 
`import {UserOperation, UserOperationLib} from "@account-abstraction/contracts/interfaces/UserOperation.sol";`
no?

2023-07-23 10:28 UTC, leonprou commented on contracts/verifying/FuseVerifyingSingletonPaymaster.sol
>      function withdrawTo(
Since it's not receives an address as an argument `withdrawTo` is misleading.  We can call with withdrawFunds.

2023-07-23 10:28 UTC, leonprou commented on contracts/common/Errors.sol
> +    error SponsorCannotBeZero();
should be `SponsorIdCannotBeZero`, no?

2023-07-23 10:28 UTC, leonprou commented on contracts/verifying/FuseVerifyingSingletonPaymaster.sol
> +contract FuseVerifyingSingletonPaymaster is
Let's look for a name that would explain the funcionality

2023-07-23 10:28 UTC, leonprou commented on contracts/verifying/PaymasterHelpers.sol
> +    uint48 validUntil;
where do we check those validations?

2023-07-23 10:28 UTC, leonprou commented on contracts/verifying/PaymasterHelpers.sol
> +    bytes12 sponsorId;
I've went over the docs of Solidity 
- **word size** - EVM word size is 256 bits, so even if you use a data that needs less size it still will take 256 bits in the memory - [reference](https://learnevm.com/chapters/evm/binary#the-256-bit-word-size).
- **storage  slots** - EVM stores data in slots also in slots of 256 bits, in case of structs in can optimize and store multiple types in one slot.
- On other hand bytes are not the common data type for storing ids, they usually represent raw data. 

 I would be glad if we can change this to something like uint96 (bytes12 is uint)

2023-07-25 08:46 UTC, maorstamati reviewed
@leonprou I resolved most and made some comments

2023-07-25 08:46 UTC, maorstamati commented on .deps/npm/@account-abstraction/contracts@0.5.0/interfaces/UserOperation.sol
> +pragma solidity ^0.8.12;
Not sure if I understand, this file is a dependency that is automatically installed I guess. 
I already import those in like you suggested contracts/verifying/FuseVerifyingSingletonPaymaster.sol

2023-07-25 08:46 UTC, maorstamati commented on contracts/verifying/FuseVerifyingSingletonPaymaster.sol
> +contract FuseVerifyingSingletonPaymaster is
I'm open to your suggestions

2023-07-25 08:46 UTC, maorstamati commented on contracts/verifying/PaymasterHelpers.sol
> +    uint48 validUntil;
It's checked in the `_packValidationData` function which is imported from `@account-abstraction/contracts/core/Helpers.sol`

2024-03-24 18:10 UTC, LiorAgnin approved these changes
LGTM!

2024-03-24 18:10 UTC, merged